services:
  # Backend API
  - type: web
    name: hotel-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://your-frontend.onrender.com

databases:
  # PostgreSQL Database
  - name: hotel-db
    databaseName: hotel_db
    user: hotel_user
    region: oregon
    plan: free
